//Global
export const SET_GLOBAL_LOADING = 'SET_GLOBAL_LOADING';
export const RESET_GLOBAL_LOADING = 'RESET_GLOBAL_LOADING';

//Auth
export const REQUEST__LOGIN = 'REQUEST__LOGIN';
export const SUCCESS__LOGIN = 'SUCCESS__LOGIN';
export const ERROR__LOGIN = 'ERROR__LOGIN';

export const REQUEST__SIGNUP = 'REQUEST__SIGNUP';
export const SUCCESS__SIGNUP = 'SUCCESS__SIGNUP';
export const ERROR__SIGNUP = 'ERROR__SIGNUP';

export const REQUEST__EMAIL_VERIFICATION = 'REQUEST__EMAIL_VERIFICATION';
export const SUCCESS__EMAIL_VERIFICATION = 'SUCCESS__EMAIL_VERIFICATION';
export const ERROR__EMAIL_VERIFICATION = 'ERROR__EMAIL_VERIFICATION';

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';

export const LOGOUT = 'LOGOUT';