//Global
export const SET_GLOBAL_LOADING = 'SET_GLOBAL_LOADING';
export const RESET_GLOBAL_LOADING = 'RESET_GLOBAL_LOADING';

export const SET_GLOBAL_APP_URL = 'SET_GLOBAL_APP_URL';
export const RESET_GLOBAL_APP_URL = 'RESET_GLOBAL_APP_URL';

export const SET_GLOBAL_THEME = 'SET_GLOBAL_THEME';
export const RESET_GLOBAL_THEME = 'RESET_GLOBAL_THEME';

export const SET_GLOBAL_PAGE_TITLE = 'SET_GLOBAL_PAGE_TITLE';
export const RESET_GLOBAL_PAGE_TITLE = 'RESET_GLOBAL_PAGE_TITLE';

//Auth
export const REQUEST__LOGIN = 'REQUEST__LOGIN';
export const SUCCESS__LOGIN = 'SUCCESS__LOGIN';
export const ERROR__LOGIN = 'ERROR__LOGIN';

export const REQUEST__SIGNUP = 'REQUEST__SIGNUP';
export const SUCCESS__SIGNUP = 'SUCCESS__SIGNUP';
export const ERROR__SIGNUP = 'ERROR__SIGNUP';

export const REQUEST__EMAIL_VERIFICATION = 'REQUEST__EMAIL_VERIFICATION';
export const SUCCESS__EMAIL_VERIFICATION = 'SUCCESS__EMAIL_VERIFICATION';
export const ERROR__EMAIL_VERIFICATION = 'ERROR__EMAIL_VERIFICATION';

export const REQUEST__ACCOUNT = 'REQUEST__ACCOUNT';
export const SUCCESS__ACCOUNT = 'SUCCESS__ACCOUNT';
export const ERROR__ACCOUNT = 'ERROR__ACCOUNT';

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const RESET_AUTH_REDIRECT = 'RESET_AUTH_REDIRECT';

export const SET_ACCOUNT = 'SET_ACCOUNT';
export const RESET_ACCOUNT = 'RESET_ACCOUNT';

export const LOGOUT = 'LOGOUT';


//User

export const REQUEST__CREATE_INSTITUTE_GROUP = 'REQUEST__CREATE_INSTITUTE_GROUP';
export const SUCCESS__CREATE_INSTITUTE_GROUP = 'SUCCESS__CREATE_INSTITUTE_GROUP';
export const ERROR__CREATE_INSTITUTE_GROUP = 'ERROR__CREATE_INSTITUTE_GROUP';
 


//InstituteGroup

export const REQUEST__CREATE_CAMPUS = 'REQUEST__CREATE_CAMPUS';
export const SUCCESS__CREATE_CAMPUS = 'SUCCESS__CREATE_CAMPUS';
export const ERROR__CREATE_CAMPUS = 'ERROR__CREATE_CAMPUS';
 
export const REQUEST__CAMPUSES = 'REQUEST__CAMPUSES';
export const SUCCESS__CAMPUSES = 'SUCCESS__CAMPUSES';
export const ERROR__CAMPUSES = 'ERROR__CAMPUSES';
 
export const REQUEST__CREATE_SUBSCRIPTION = 'REQUEST__CREATE_SUBSCRIPTION';
export const SUCCESS__CREATE_SUBSCRIPTION = 'SUCCESS__CREATE_SUBSCRIPTION';
export const ERROR__CREATE_SUBSCRIPTION = 'ERROR__CREATE_SUBSCRIPTION';
 
export const REQUEST__SUBSCRIPTION_FAIL = 'REQUEST__SUBSCRIPTION_FAIL';
export const SUCCESS__SUBSCRIPTION_FAIL = 'SUCCESS__SUBSCRIPTION_FAIL';
export const ERROR__SUBSCRIPTION_FAIL = 'ERROR__SUBSCRIPTION_FAIL';
 