//Global
export const SET_GLOBAL_LOADING = 'SET_GLOBAL_LOADING';
export const RESET_GLOBAL_LOADING = 'RESET_GLOBAL_LOADING';

export const SET_GLOBAL_APP_URL = 'SET_GLOBAL_APP_URL';
export const RESET_GLOBAL_APP_URL = 'RESET_GLOBAL_APP_URL';

export const SET_GLOBAL_THEME = 'SET_GLOBAL_THEME';
export const RESET_GLOBAL_THEME = 'RESET_GLOBAL_THEME';

export const SET_GLOBAL_PAGE_TITLE = 'SET_GLOBAL_PAGE_TITLE';
export const RESET_GLOBAL_PAGE_TITLE = 'RESET_GLOBAL_PAGE_TITLE';

//Auth
export const REQUEST__LOGIN = 'REQUEST__LOGIN';
export const SUCCESS__LOGIN = 'SUCCESS__LOGIN';
export const ERROR__LOGIN = 'ERROR__LOGIN';

export const REQUEST__SIGNUP = 'REQUEST__SIGNUP';
export const SUCCESS__SIGNUP = 'SUCCESS__SIGNUP';
export const ERROR__SIGNUP = 'ERROR__SIGNUP';

export const REQUEST__EMAIL_VERIFICATION = 'REQUEST__EMAIL_VERIFICATION';
export const SUCCESS__EMAIL_VERIFICATION = 'SUCCESS__EMAIL_VERIFICATION';
export const ERROR__EMAIL_VERIFICATION = 'ERROR__EMAIL_VERIFICATION';

export const REQUEST__ACCOUNT = 'REQUEST__ACCOUNT';
export const SUCCESS__ACCOUNT = 'SUCCESS__ACCOUNT';
export const ERROR__ACCOUNT = 'ERROR__ACCOUNT';

export const REQUEST__ACCOUNTS = 'REQUEST__ACCOUNTS';
export const SUCCESS__ACCOUNTS = 'SUCCESS__ACCOUNTS';
export const ERROR__ACCOUNTS = 'ERROR__ACCOUNTS';

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const RESET_AUTH_REDIRECT = 'RESET_AUTH_REDIRECT';

export const SET_ACCOUNT = 'SET_ACCOUNT';
export const RESET_ACCOUNT = 'RESET_ACCOUNT';

export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';

export const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';
export const RESET_SUBSCRIPTION = 'RESET_SUBSCRIPTION';

export const LOGOUT = 'LOGOUT';


//User

export const REQUEST__CREATE_INSTITUTE_GROUP = 'REQUEST__CREATE_INSTITUTE_GROUP';
export const SUCCESS__CREATE_INSTITUTE_GROUP = 'SUCCESS__CREATE_INSTITUTE_GROUP';
export const ERROR__CREATE_INSTITUTE_GROUP = 'ERROR__CREATE_INSTITUTE_GROUP';
 
export const REQUEST__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE = 'REQUEST__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE';
export const SUCCESS__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE = 'SUCCESS__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE';
export const ERROR__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE = 'ERROR__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE';
 


//InstituteGroup

export const REQUEST__CREATE_CAMPUS = 'REQUEST__CREATE_CAMPUS';
export const SUCCESS__CREATE_CAMPUS = 'SUCCESS__CREATE_CAMPUS';
export const ERROR__CREATE_CAMPUS = 'ERROR__CREATE_CAMPUS';
 
export const REQUEST__CAMPUSES = 'REQUEST__CAMPUSES';
export const SUCCESS__CAMPUSES = 'SUCCESS__CAMPUSES';
export const ERROR__CAMPUSES = 'ERROR__CAMPUSES';
 
export const REQUEST__CREATE_SUBSCRIPTION = 'REQUEST__CREATE_SUBSCRIPTION';
export const SUCCESS__CREATE_SUBSCRIPTION = 'SUCCESS__CREATE_SUBSCRIPTION';
export const ERROR__CREATE_SUBSCRIPTION = 'ERROR__CREATE_SUBSCRIPTION';
 
export const REQUEST__SUBSCRIPTION_FAIL = 'REQUEST__SUBSCRIPTION_FAIL';
export const SUCCESS__SUBSCRIPTION_FAIL = 'SUCCESS__SUBSCRIPTION_FAIL';
export const ERROR__SUBSCRIPTION_FAIL = 'ERROR__SUBSCRIPTION_FAIL';
 
export const REQUEST__UPLOAD_CAMPUS_PROFILE_IMAGE = 'REQUEST__UPLOAD_CAMPUS_PROFILE_IMAGE';
export const SUCCESS__UPLOAD_CAMPUS_PROFILE_IMAGE = 'SUCCESS__UPLOAD_CAMPUS_PROFILE_IMAGE';
export const ERROR__UPLOAD_CAMPUS_PROFILE_IMAGE = 'ERROR__UPLOAD_CAMPUS_PROFILE_IMAGE';
 
export const REQUEST__GET_CAMPUSES = 'REQUEST__GET_CAMPUSES';
export const SUCCESS__GET_CAMPUSES = 'SUCCESS__GET_CAMPUSES';
export const ERROR__GET_CAMPUSES = 'ERROR__GET_CAMPUSES';

export const SET_CAMPUS_SHOULD_LOAD = 'SET_CAMPUS_SHOULD_LOAD'
export const RESET_CAMPUS_SHOULD_LOAD = 'RESET_CAMPUS_SHOULD_LOAD'

export const SET_IS_SUB_NOW = 'SET_IS_SUB_NOW'
export const RESET_IS_SUB_NOW = 'RESET_IS_SUB_NOW'
