
//Auth
export const REQUEST__LOGIN = 'REQUEST__LOGIN';
export const SUCCESS__LOGIN = 'SUCCESS__LOGIN';
export const ERROR__LOGIN = 'ERROR__LOGIN';

export const REQUEST__SIGNUP = 'REQUEST__SIGNUP';
export const SUCCESS__SIGNUP = 'SUCCESS__SIGNUP';
export const ERROR__SIGNUP = 'ERROR__SIGNUP';

export const REQUEST__EMAIL_VERIFICATION = 'REQUEST__EMAIL_VERIFICATION';
export const SUCCESS__EMAIL_VERIFICATION = 'SUCCESS__EMAIL_VERIFICATION';
export const ERROR__EMAIL_VERIFICATION = 'ERROR__EMAIL_VERIFICATION';

export const REQUEST__ACCOUNT = 'REQUEST__ACCOUNT';
export const SUCCESS__ACCOUNT = 'SUCCESS__ACCOUNT';
export const ERROR__ACCOUNT = 'ERROR__ACCOUNT';

export const REQUEST__ACCOUNTS = 'REQUEST__ACCOUNTS';
export const SUCCESS__ACCOUNTS = 'SUCCESS__ACCOUNTS';
export const ERROR__ACCOUNTS = 'ERROR__ACCOUNTS';

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const RESET_AUTH_REDIRECT = 'RESET_AUTH_REDIRECT';

export const SET_ACCOUNT = 'SET_ACCOUNT';
export const RESET_ACCOUNT = 'RESET_ACCOUNT';

export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';

export const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';
export const RESET_SUBSCRIPTION = 'RESET_SUBSCRIPTION';

export const LOGOUT = 'LOGOUT';
