export const REQUEST__CREATE_CLASS = "REQUEST__CREATE_CLASS";
export const SUCCESS__CREATE_CLASS = "SUCCESS__CREATE_CLASS";
export const ERROR__CREATE_CLASS = "ERROR__CREATE_CLASS";

export const REQUEST__STUDENT_ADMISSION_REQUESTS =
  "REQUEST__STUDENT_ADMISSION_REQUESTS";
export const SUCCESS__STUDENT_ADMISSION_REQUESTS =
  "SUCCESS__STUDENT_ADMISSION_REQUESTS";
export const ERROR__STUDENT_ADMISSION_REQUESTS =
  "ERROR__STUDENT_ADMISSION_REQUESTS";

export const REQUEST__ACCEPT_STUDENT_ADMISSION_REQUEST =
  "REQUEST__ACCEPT_STUDENT_ADMISSION_REQUEST";
export const SUCCESS__ACCEPT_STUDENT_ADMISSION_REQUEST =
  "SUCCESS__ACCEPT_STUDENT_ADMISSION_REQUEST";
export const ERROR__ACCEPT_STUDENT_ADMISSION_REQUEST =
  "ERROR__ACCEPT_STUDENT_ADMISSION_REQUEST";

export const REQUEST__REJECT_STUDENT_ADMISSION_REQUEST =
  "REQUEST__REJECT_STUDENT_ADMISSION_REQUEST";
export const SUCCESS__REJECT_STUDENT_ADMISSION_REQUEST =
  "SUCCESS__REJECT_STUDENT_ADMISSION_REQUEST";
export const ERROR__REJECT_STUDENT_ADMISSION_REQUEST =
  "ERROR__REJECT_STUDENT_ADMISSION_REQUEST";

export const REQUEST__SEARCH_CLASS = "REQUEST__SEARCH_CLASS";
export const SUCCESS__SEARCH_CLASS = "SUCCESS__SEARCH_CLASS";
export const ERROR__SEARCH_CLASS = "ERROR__SEARCH_CLASS";
