export const REQUEST__CREATE_CLASS = "REQUEST__CREATE_CLASS";
export const SUCCESS__CREATE_CLASS = "SUCCESS__CREATE_CLASS";
export const ERROR__CREATE_CLASS = "ERROR__CREATE_CLASS";

export const REQUEST__STUDENT_ADMISSION_REQUESTS =
  "REQUEST__STUDENT_ADMISSION_REQUESTS";
export const SUCCESS__STUDENT_ADMISSION_REQUESTS =
  "SUCCESS__STUDENT_ADMISSION_REQUESTS";
export const ERROR__STUDENT_ADMISSION_REQUESTS =
  "ERROR__STUDENT_ADMISSION_REQUESTS";

export const REQUEST__TEACHER_JOIN_REQUESTS = "REQUEST__TEACHER_JOIN_REQUESTS";
export const SUCCESS__TEACHER_JOIN_REQUESTS = "SUCCESS__TEACHER_JOIN_REQUESTS";
export const ERROR__TEACHER_JOIN_REQUESTS = "ERROR__TEACHER_JOIN_REQUESTS";

export const REQUEST__ACCEPT_STUDENT_ADMISSION_REQUEST =
  "REQUEST__ACCEPT_STUDENT_ADMISSION_REQUEST";
export const SUCCESS__ACCEPT_STUDENT_ADMISSION_REQUEST =
  "SUCCESS__ACCEPT_STUDENT_ADMISSION_REQUEST";
export const ERROR__ACCEPT_STUDENT_ADMISSION_REQUEST =
  "ERROR__ACCEPT_STUDENT_ADMISSION_REQUEST";

export const REQUEST__ACCEPT_TEACHER_JOIN_REQUEST =
  "REQUEST__ACCEPT_TEACHER_JOIN_REQUEST";
export const SUCCESS__ACCEPT_TEACHER_JOIN_REQUEST =
  "SUCCESS__ACCEPT_TEACHER_JOIN_REQUEST";
export const ERROR__ACCEPT_TEACHER_JOIN_REQUEST =
  "ERROR__ACCEPT_TEACHER_JOIN_REQUEST";

export const REQUEST__REJECT_STUDENT_ADMISSION_REQUEST =
  "REQUEST__REJECT_STUDENT_ADMISSION_REQUEST";
export const SUCCESS__REJECT_STUDENT_ADMISSION_REQUEST =
  "SUCCESS__REJECT_STUDENT_ADMISSION_REQUEST";
export const ERROR__REJECT_STUDENT_ADMISSION_REQUEST =
  "ERROR__REJECT_STUDENT_ADMISSION_REQUEST";

export const REQUEST__REJECT_TEACHER_JOIN_REQUEST =
  "REQUEST__REJECT_TEACHER_JOIN_REQUEST";
export const SUCCESS__REJECT_TEACHER_JOIN_REQUEST =
  "SUCCESS__REJECT_TEACHER_JOIN_REQUEST";
export const ERROR__REJECT_TEACHER_JOIN_REQUEST =
  "ERROR__REJECT_TEACHER_JOIN_REQUEST";

export const REQUEST__GET_CLASSES = "REQUEST__GET_CLASSES";
export const SUCCESS__GET_CLASSES = "SUCCESS__GET_CLASSES";
export const ERROR__GET_CLASSES = "ERROR__GET_CLASSES";
