//Global
export const SET_GLOBAL_LOADING = 'SET_GLOBAL_LOADING';
export const RESET_GLOBAL_LOADING = 'RESET_GLOBAL_LOADING';

export const SET_GLOBAL_APP_URL = 'SET_GLOBAL_APP_URL';
export const RESET_GLOBAL_APP_URL = 'RESET_GLOBAL_APP_URL';

export const SET_GLOBAL_THEME = 'SET_GLOBAL_THEME';
export const RESET_GLOBAL_THEME = 'RESET_GLOBAL_THEME';

export const SET_GLOBAL_PAGE_TITLE = 'SET_GLOBAL_PAGE_TITLE';
export const RESET_GLOBAL_PAGE_TITLE = 'RESET_GLOBAL_PAGE_TITLE';

export const SET_BACK_BTN = 'SET_BACK_BTN';
export const RESET_BACK_BTN = 'RESET_BACK_BTN';

export const SET_POST_MODAL_OPEN = 'SET_POST_MODAL_OPEN';
export const RESET_POST_MODAL_OPEN = 'RESET_POST_MODAL_OPEN';
