
//InstituteGroup

export const REQUEST__CREATE_CAMPUS = 'REQUEST__CREATE_CAMPUS';
export const SUCCESS__CREATE_CAMPUS = 'SUCCESS__CREATE_CAMPUS';
export const ERROR__CREATE_CAMPUS = 'ERROR__CREATE_CAMPUS';
 
export const REQUEST__CAMPUSES = 'REQUEST__CAMPUSES';
export const SUCCESS__CAMPUSES = 'SUCCESS__CAMPUSES';
export const ERROR__CAMPUSES = 'ERROR__CAMPUSES';
 
export const REQUEST__CREATE_SUBSCRIPTION = 'REQUEST__CREATE_SUBSCRIPTION';
export const SUCCESS__CREATE_SUBSCRIPTION = 'SUCCESS__CREATE_SUBSCRIPTION';
export const ERROR__CREATE_SUBSCRIPTION = 'ERROR__CREATE_SUBSCRIPTION';
 
export const REQUEST__SUBSCRIPTION_FAIL = 'REQUEST__SUBSCRIPTION_FAIL';
export const SUCCESS__SUBSCRIPTION_FAIL = 'SUCCESS__SUBSCRIPTION_FAIL';
export const ERROR__SUBSCRIPTION_FAIL = 'ERROR__SUBSCRIPTION_FAIL';
 
export const REQUEST__UPLOAD_CAMPUS_PROFILE_IMAGE = 'REQUEST__UPLOAD_CAMPUS_PROFILE_IMAGE';
export const SUCCESS__UPLOAD_CAMPUS_PROFILE_IMAGE = 'SUCCESS__UPLOAD_CAMPUS_PROFILE_IMAGE';
export const ERROR__UPLOAD_CAMPUS_PROFILE_IMAGE = 'ERROR__UPLOAD_CAMPUS_PROFILE_IMAGE';
 
export const REQUEST__GET_CAMPUSES = 'REQUEST__GET_CAMPUSES';
export const SUCCESS__GET_CAMPUSES = 'SUCCESS__GET_CAMPUSES';
export const ERROR__GET_CAMPUSES = 'ERROR__GET_CAMPUSES';

export const SET_CAMPUS_SHOULD_LOAD = 'SET_CAMPUS_SHOULD_LOAD'
export const RESET_CAMPUS_SHOULD_LOAD = 'RESET_CAMPUS_SHOULD_LOAD'

export const SET_IS_SUB_NOW = 'SET_IS_SUB_NOW'
export const RESET_IS_SUB_NOW = 'RESET_IS_SUB_NOW'
