//User

export const REQUEST__CREATE_INSTITUTE_GROUP =
  "REQUEST__CREATE_INSTITUTE_GROUP";
export const SUCCESS__CREATE_INSTITUTE_GROUP =
  "SUCCESS__CREATE_INSTITUTE_GROUP";
export const ERROR__CREATE_INSTITUTE_GROUP = "ERROR__CREATE_INSTITUTE_GROUP";

export const REQUEST__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE =
  "REQUEST__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE";
export const SUCCESS__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE =
  "SUCCESS__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE";
export const ERROR__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE =
  "ERROR__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE";

export const REQUEST__REGISTER_NOTIF_TOKEN = "REQUEST__REGISTER_NOTIF_TOKEN";
export const SUCCESS__REGISTER_NOTIF_TOKEN = "SUCCESS__REGISTER_NOTIF_TOKEN";
export const ERROR__REGISTER_NOTIF_TOKEN = "ERROR__REGISTER_NOTIF_TOKEN";

export const REQUEST__FORGOT_PASSWORD = "REQUEST__FORGOT_PASSWORD";
export const SUCCESS__FORGOT_PASSWORD = "SUCCESS__FORGOT_PASSWORD";
export const ERROR__FORGOT_PASSWORD = "ERROR__FORGOT_PASSWORD";

export const REQUEST__RESET_PASSWORD = "RESET__RESET_PASSWORD";
export const SUCCESS__RESET_PASSWORD = "SUCCESS__RESET_PASSWORD";
export const ERROR__RESET_PASSWORD = "ERROR__RESET_PASSWORD";

export const REQUEST__GET_CAMPUS = "RESET__GET_CAMPUS";
export const SUCCESS__GET_CAMPUS = "SUCCESS__GET_CAMPUS";
export const ERROR__GET_CAMPUS = "ERROR__GET_CAMPUS";

export const REQUEST__SEARCH_CLASS = "REQUEST__SEARCH_CLASS";
export const SUCCESS__SEARCH_CLASS = "SUCCESS__SEARCH_CLASS";
export const ERROR__SEARCH_CLASS = "ERROR__SEARCH_CLASS";
