//User

export const REQUEST__CREATE_INSTITUTE_GROUP = 'REQUEST__CREATE_INSTITUTE_GROUP';
export const SUCCESS__CREATE_INSTITUTE_GROUP = 'SUCCESS__CREATE_INSTITUTE_GROUP';
export const ERROR__CREATE_INSTITUTE_GROUP = 'ERROR__CREATE_INSTITUTE_GROUP';
 
export const REQUEST__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE = 'REQUEST__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE';
export const SUCCESS__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE = 'SUCCESS__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE';
export const ERROR__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE = 'ERROR__UPLOAD_INSTITUTE_GROUP_PROFILE_IMAGE';
 
export const REQUEST__NOTIF_TOKEN = 'REQUEST__NOTIF_TOKEN';
export const SUCCESS__NOTIF_TOKEN = 'SUCCESS__NOTIF_TOKEN';
export const ERROR__NOTIF_TOKEN = 'ERROR__NOTIF_TOKEN';
 
